env:
    - ARCH=x86
language: python
sudo: false
python:
    - "2.7"
cache:
  directories:
    - "$HOME/.pip-cache/"
    - "/home/travis/virtualenv/python2.7"
install: 
    - "pip install -r client/requirements.txt"
    - "pip install python-coveralls"
    - "pip install coverage"
    - "pip install flake8"
script:
    - "coverage run -m unittest discover"
after_success:
    - "coverage report"
    - "coveralls"
